### PR TITLE
Better contact handling in email client senders

### LINKED ISSUE #31: Panic on send certificates if missing contact
There is a bug in the sending certificates code that caused a panic, possibly because there was no billing contact. ﻿﻿
﻿This also means that Rotational's status was not correctly updated. ﻿
﻿
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8fc0a6]

goroutine 654 [running]:
github.com/trisacrypto/directory/pkg/gds/models/v1.GetContactVerification(0x0, 0xc00044c4b0, 0x0, 0x0, 0xc00044f380, 0x11)
	/srv/build/pkg/gds/models/v1/models.go:38 +0x26
github.com/trisacrypto/directory/pkg/gds/emails.(*EmailManager).SendDeliverCertificates(0xc00032e460, 0xc0000cda40, 0xc00003aa68, 0x11, 0xc00044c0f0, 0x0)
	/srv/build/pkg/gds/emails/client.go:185 +0x22b
github.com/trisacrypto/directory/pkg/gds.(*Server).downloadCertificateRequest(0xc00042d040, 0xc0000f8f00)
	/srv/build/pkg/gds/certs.go:329 +0xbd6
created by github.com/trisacrypto/directory/pkg/gds.(*Server).checkCertificateRequest
	/srv/build/pkg/gds/certs.go:226 +0x5f7
```

### LINKED ISSUE #32: Update registration review email sent to TRISA admins
Use protojson marshaling to output the VASP record when sending to TRISA admins for better readability (e.g. will ensure that enums are strings instead of integers), then remarshal into YAML or a format that is easier to read than raw JSON.

### PR DESCRIPTION
**Pull request by bbengfort**
Performs better handling of sending emails to technical, admin, billing,
and legal contacts. First, a check is added to ensure the contact is not
nil and that it has an email address, otherwise it is skipped. Sending
does not stop on the first error, but all email addresses are tried to
make sure at least one email can get out. The number of errors are
reported via logging rather than returned. If no messages were delivered
then the function returns an error.

This PR also updates the Registration Review email to be nicely rendered
YAML with string enums and no empty fields.

Fixes #31
Fixes #32

### CODE REVIEW

File: pkg/gds/certs.go [hunk 1]
```diff
@@ -327,7 +327,9 @@ func (s *Server) downloadCertificateRequest(r *models.CertificateRequest) {
 
 	// Email the certificates to the technical contacts
 	if err = s.email.SendDeliverCertificates(vasp, path); err != nil {
+		// If there is an error delivering emails, return here so we don't mark as completed
 		log.Error().Err(err).Msg("could not deliver certificates to technical contact")
+		return
```
Comment (rebeccabilbro) [inline pkg/gds/certs.go:332]: 👍

File: pkg/gds/emails/client.go [hunk 2]
```diff
@@ -83,25 +91,49 @@ func (m *EmailManager) SendVerifyContacts(vasp *pb.VASP) (err error) {
...
-	if data, err = json.MarshalIndent(vasp, "", "  "); err != nil {
+	if data, err = jsonpb.Marshal(vasp); err != nil {
 		return err
 	}
 
+	// Convert JSON to YAML to make it more human readable
+	// If the conversion fails, then the JSON data will be kept
+	if yamlData, err := yaml.JSONToYAML(data); err == nil {
+		data = yamlData
+	}
```
Comment (rebeccabilbro) [inline pkg/gds/emails/client.go:135]: This should make reviewing the emails easier!

File: pkg/gds/emails/client.go [hunk 3]
```diff
@@ -83,25 +91,49 @@ func (m *EmailManager) SendVerifyContacts(vasp *pb.VASP) (err error) {
...
 }
 
 // SendReviewRequest is a shortcut for iComply verification in which we simply send
 // an email to the TRISA admins and have them manually verify registrations.
 func (m *EmailManager) SendReviewRequest(vasp *pb.VASP) (err error) {
+	jsonpb := protojson.MarshalOptions{
+		Multiline:       false,
+		AllowPartial:    true,
+		UseProtoNames:   true,
+		UseEnumNumbers:  false,
```
Comment (rebeccabilbro) [inline pkg/gds/emails/client.go:122]: 👍

**Review by rebeccabilbro — APPROVED** [review]
Looks good; should nicely resolve several of the bugs we noticed last week &mdash; thank you @bbengfort !
